name = "Island"
author = "Petingoso"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5c1bb81e8a223cf514eefa92c913d2d2c23e357dc1457afb48af6b977edb11e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
