name = "Island"
author = "Petingoso"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50f49f06938e98134cc96f7f01f57609ed75a6c6def16cb5bae1cab482878b42"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
