name = "Island"
author = "Petingoso"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "005e202cf321ed804e27e70159f09b2f5534f516b369334c071c2ffcfc9390e0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
